version: '3'
services:
  client:
    build:
      context: '.'
      dockerfile: './Dockerfile'
    ports:
      - '8080:8080'
    stdin_open: true
    volumes:
      - .:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_SERVER_API_URL=http://localhost:7100/graphql
      - NODE_ENV=development
