version: '3'
services:
  server-api-getaway:
    build:
      context: "."
      dockerfile: "./server-api-getaway/Dockerfile"
      depends_on:
        - db
      ports:
        - "4000:4000"
      volumes:
        - ./server-api-getaway:/opt/app
  db:
    image: postgres
    environment:
      - POSTGRES_DB=memo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres