version: '3'
services:
  server-api-getaway:
    build:
      context: "."
      dockerfile: "./server-api-gateway/Dockerfile"
    depends_on:
      - db
      - redis
    ports:
      - "7100:7100"
    volumes:
      - ./server-api-gateway:/usr/src/app/server-api-gateway
    environment:
      CHOKIDAR_USEPOLLING: "true"
    environment:
      - REDIS_URL=redis://cache
      - DATABASE_URL=postgres://postgres:postgres@db:5432/memo
      - DATABASE_PORT=5432
      - DATABASE_HOST=host.docker.internal
      - POSTGRES_DB=memo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PORT=7100

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=memo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    ports:
        - "5433:5432"

  redis:
    image: redis
    container_name: cache
    restart: always
    ports:
      - 6379:6379

  client:
    build:
      context: "."
      dockerfile: "./client/Dockerfile"
    ports:
      - "8080:8080"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    volumes:
      - ./client:/usr/src/app/client
    environment:
      - SERVER_API_URL=http://localhost:7100/graphql
      

  
volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog: 
    driver: local