version: '3'
services:
  server-api-getaway:
    build:
      context: "."
      dockerfile: "./server-api-gateway/Dockerfile"
    depends_on:
      - db
    ports:
      - "7100:7100"
    volumes:
      - ./server-api-gateway:/usr/src/app
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=memo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432    