version: "3"
services:
  server-api-getaway:
    build:
      context: "."
      dockerfile: "./server-api-gateway/Dockerfile"
    depends_on:
      - db
      - redis
    ports:
      - "7100:7100"
    volumes:
      - ./server-api-gateway:/usr/src/app/server-api-gateway
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REDIS_URL=redis://cache
      - DATABASE_URL=postgres://postgres:postgres@db:5432/memo
      - DATABASE_PORT=5432
      - DATABASE_HOST=host.docker.internal
      - POSTGRES_DB=memo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PORT=7100

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=memo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    ports:
      - "5433:5432"

  server-user-service:
    build:
      context: "."
      dockerfile: "./server-user-service/Dockerfile"
    depends_on:
      - db_user
      - redis
    ports:
      - "7200:7200"
    volumes:
      - ./server-user-service:/usr/src/app/server-user-service
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REDIS_URL=redis://cache
      - DATABASE_URL=postgres://postgres:postgres@db_user:3306/memo_user
      - DATABASE_PORT=3306
      - DATABASE_HOST=host.docker.internal
      - POSTGRES_DB=memo_user
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PORT=7200

  db_user:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=memo_user
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    ports:
      - 0.0.0.0:7201:3306

  redis:
    image: redis
    container_name: cache
    restart: always
    ports:
      - 6379:6379

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
